### ISSUE TITLE
Update to the latest version of OT Monitor

### ISSUE THREAD

**Issue by user34756361233** [basnijholt/addon-otmonitor#48]
Hi Bas,

would it be possible to update to the latest version of OT monitor as found on https://otgw.tclcode.com/otmonitor.html?

Tia

Han

**Comment by fliphess** [comment]
@user34756361233: The [dockerfile](https://github.com/basnijholt/addon-otmonitor/blob/master/otmonitor/Dockerfile#L18) uses the git archive from the master branch. 

Because the addon itself does not provide a versioned container in a container registry, the docker container is build on the machine running home assistant. 

... So to get the latest version, all you have to do is rebuild the image using the "Rebuild" button in the otmonitor addon panel.

**Comment by user34756361233** [comment]
Thank you. Didnt know that
